spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://my-rds-instance.cqwxdf1sdeiw.ap-northeast-2.rds.amazonaws.com:3306/my_rds_name
    username: admin
    password: qogustj50
    hikari:
      maximum-pool-size: 10