name: meetup Server CI/CD with Docker

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 🍃 JDK 17로 설정합니다.
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'


    
    - name: 🍃 gradle build를 위한 권한을 부여합니다.
      run: chmod +x gradlew
      
    - name: 🍃 gradle build 중입니다.
      run: ./gradlew build -x test
        
    - name: 🍃 docker image build 후 docker hub에 push합니다.
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t haul123/qogustj:latest .

        docker push haul123/qogustj:latest
        
    - name: 🍃 deploy.sh 파일을 EC2 server로 전달합니다.
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ec2-3-39-17-213.ap-northeast-2.compute.amazonaws.com
        key: MIIEowIBAAKCAQEA6dGGc8RU+H/lnBub6Q0m7DlNS3I/98S1c7YpF8kDZPEHgIHIpQ7bNSqA2jCYVpakmiUCln5id1Tzzd770/2BlliOkq0ryUvLk2SpmWUTBUxZj8DRRIBPMi3uVk8GFD8V0lJphhJidUkrSTn/hK9f5/ihRXMm628O6smInEDzEDaIWyUL8LWJXlqykjnmDt7OFV+rqr7kN10QA0SyMprC2j2kkpKw/h3LXgAw1/eeZmoU/boqR0G99geynVoHgb/bCnSgQChpzX3BX+Vcm32kpuYIvRmjPGGi2J+JkXNjNKvGgqT3ltOoytBUYw74yId1mRf+nUnXT+/RLzrYdbeJQIDAQABAoIBAHkpAarribxbSffitp/FGO4/ozX9NfiGDiCvvAt/NisQWvrURcyCLkUWiT6G/melhzqILUrOIrtkoiTi5sGOihWK0sGQTJF/G+cMeYy4fBU5/P9znLYqjEua9p9iIDlT8F0wwmebTape6yuSSHQXrottCPwz7IgEnLHi+qsHUfAfIlvlqOJ/WRmhcyJPIymOxgqlltGHkZGqVMzi4R/gWv8WQyxAH+hP0DwDms1uIKUmUyaODdBxR2OfuTKOx9AaSGfe/Jn+w5pmYtFMd3qf4A4sg3v8HfOuVh082ZhNulkg5wIvuudj8yTrG3PTWvBUujZe/GTEHJ7m6AZH5QzywECgYEA/745Vrz49FwpIrh3yFA7PlPr6kvqalKO5/xZoa4bmbp/C/mYlnlPPECVyTzIw2QIr6GdbXrTtXdiqszNI1PLaom15KzGlISCP09jVBdwz+pvHga0ee7GNjXpPu8CjuCb8B94WSCyyE24OUGvMVCkKBBP962QxhlKSn+KlfBvDb0CgYEA6g2pjSKa3SWfyP90fBPb69RRXUMnA3lnlV15i6ofHDfi68neZ3xAJhDwNW1jTZD/192f0ZqFI+fsKW5dVNRbcYXs+cOwBHEY3PXgkAsNbApGslv2PomPZpXz+0r/K2TN9QQIGoZsZ4XmYJqzAL4/q7EtO0xjoN9s8Mrs9eo1IkCgYEAgsHbx0FveGD2l04B0GVVJRT7dhvCiwITFwGrQkMm0X7NHm5LWgREQuYyr2VosJ4g4subFjLKs+mKhRGZgQqC4sHuQjEkhyMJBR2uB3zErUmL7qo29HDk3yrJSughQrQMhsVQXyGcx1UVcBDpZil5BRLyEAyqDN85YMW9MdRws3ECgYAPBzGLzl0DNhc8YKqyIav4D9m4C/vzSTElKXeYgAZxdw3jeiues3V2BFDVYON3XbSgAREquuq0x0QJo5p03hSsZ7u94WghDQL/H8EGq/gqulTpU2XLGMS7z90zjJb2cm6xdvxSGH3t2ajKQoV48/fo4m/e7hvweqDnmfCEa6R7gQKBgHMOd+yQrHC9MO0Hmy/ku9oYWF/E5fONXJa/DibYQphMM5vn9V2QyJSt3sgzlaaJSuclGQ0BsEjXjJ1BbX0Y9YNIn2/A459TLvxoBPm+3aXIb83tQ6AhslIwqlzxeU3jZOr3OtKWazVI8gGTJh8FmQ7GPbsrY9NZ/hDnvY1XA9VN
        port: 22
        source: "./scripts/deploy.sh"
        target: "/home/ubuntu/"
        
    - name: 🍃 docker-compose.yml 파일을 EC2 server로 전달합니다.
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ec2-3-39-17-213.ap-northeast-2.compute.amazonaws.com
        key: MIIEowIBAAKCAQEA6dGGc8RU+H/lnBub6Q0m7DlNS3I/98S1c7YpF8kDZPEHgIHIpQ7bNSqA2jCYVpakmiUCln5id1Tzzd770/2BlliOkq0ryUvLk2SpmWUTBUxZj8DRRIBPMi3uVk8GFD8V0lJphhJidUkrSTn/hK9f5/ihRXMm628O6smInEDzEDaIWyUL8LWJXlqykjnmDt7OFV+rqr7kN10QA0SyMprC2j2kkpKw/h3LXgAw1/eeZmoU/boqR0G99geynVoHgb/bCnSgQChpzX3BX+Vcm32kpuYIvRmjPGGi2J+JkXNjNKvGgqT3ltOoytBUYw74yId1mRf+nUnXT+/RLzrYdbeJQIDAQABAoIBAHkpAarribxbSffitp/FGO4/ozX9NfiGDiCvvAt/NisQWvrURcyCLkUWiT6G/melhzqILUrOIrtkoiTi5sGOihWK0sGQTJF/G+cMeYy4fBU5/P9znLYqjEua9p9iIDlT8F0wwmebTape6yuSSHQXrottCPwz7IgEnLHi+qsHUfAfIlvlqOJ/WRmhcyJPIymOxgqlltGHkZGqVMzi4R/gWv8WQyxAH+hP0DwDms1uIKUmUyaODdBxR2OfuTKOx9AaSGfe/Jn+w5pmYtFMd3qf4A4sg3v8HfOuVh082ZhNulkg5wIvuudj8yTrG3PTWvBUujZe/GTEHJ7m6AZH5QzywECgYEA/745Vrz49FwpIrh3yFA7PlPr6kvqalKO5/xZoa4bmbp/C/mYlnlPPECVyTzIw2QIr6GdbXrTtXdiqszNI1PLaom15KzGlISCP09jVBdwz+pvHga0ee7GNjXpPu8CjuCb8B94WSCyyE24OUGvMVCkKBBP962QxhlKSn+KlfBvDb0CgYEA6g2pjSKa3SWfyP90fBPb69RRXUMnA3lnlV15i6ofHDfi68neZ3xAJhDwNW1jTZD/192f0ZqFI+fsKW5dVNRbcYXs+cOwBHEY3PXgkAsNbApGslv2PomPZpXz+0r/K2TN9QQIGoZsZ4XmYJqzAL4/q7EtO0xjoN9s8Mrs9eo1IkCgYEAgsHbx0FveGD2l04B0GVVJRT7dhvCiwITFwGrQkMm0X7NHm5LWgREQuYyr2VosJ4g4subFjLKs+mKhRGZgQqC4sHuQjEkhyMJBR2uB3zErUmL7qo29HDk3yrJSughQrQMhsVQXyGcx1UVcBDpZil5BRLyEAyqDN85YMW9MdRws3ECgYAPBzGLzl0DNhc8YKqyIav4D9m4C/vzSTElKXeYgAZxdw3jeiues3V2BFDVYON3XbSgAREquuq0x0QJo5p03hSsZ7u94WghDQL/H8EGq/gqulTpU2XLGMS7z90zjJb2cm6xdvxSGH3t2ajKQoV48/fo4m/e7hvweqDnmfCEa6R7gQKBgHMOd+yQrHC9MO0Hmy/ku9oYWF/E5fONXJa/DibYQphMM5vn9V2QyJSt3sgzlaaJSuclGQ0BsEjXjJ1BbX0Y9YNIn2/A459TLvxoBPm+3aXIb83tQ6AhslIwqlzxeU3jZOr3OtKWazVI8gGTJh8FmQ7GPbsrY9NZ/hDnvY1XA9VN
        port: 22
        source: "./docker-compose.yml"
        target: "/home/ubuntu/"
        
    - name: 🍃 docker hub에서 pull 후 deploy합니다.
      uses: appleboy/ssh-action@master
      with:
        username: ubuntu
        host: ec2-3-39-17-213.ap-northeast-2.compute.amazonaws.com
        key: MIIEowIBAAKCAQEA6dGGc8RU+H/lnBub6Q0m7DlNS3I/98S1c7YpF8kDZPEHgIHIpQ7bNSqA2jCYVpakmiUCln5id1Tzzd770/2BlliOkq0ryUvLk2SpmWUTBUxZj8DRRIBPMi3uVk8GFD8V0lJphhJidUkrSTn/hK9f5/ihRXMm628O6smInEDzEDaIWyUL8LWJXlqykjnmDt7OFV+rqr7kN10QA0SyMprC2j2kkpKw/h3LXgAw1/eeZmoU/boqR0G99geynVoHgb/bCnSgQChpzX3BX+Vcm32kpuYIvRmjPGGi2J+JkXNjNKvGgqT3ltOoytBUYw74yId1mRf+nUnXT+/RLzrYdbeJQIDAQABAoIBAHkpAarribxbSffitp/FGO4/ozX9NfiGDiCvvAt/NisQWvrURcyCLkUWiT6G/melhzqILUrOIrtkoiTi5sGOihWK0sGQTJF/G+cMeYy4fBU5/P9znLYqjEua9p9iIDlT8F0wwmebTape6yuSSHQXrottCPwz7IgEnLHi+qsHUfAfIlvlqOJ/WRmhcyJPIymOxgqlltGHkZGqVMzi4R/gWv8WQyxAH+hP0DwDms1uIKUmUyaODdBxR2OfuTKOx9AaSGfe/Jn+w5pmYtFMd3qf4A4sg3v8HfOuVh082ZhNulkg5wIvuudj8yTrG3PTWvBUujZe/GTEHJ7m6AZH5QzywECgYEA/745Vrz49FwpIrh3yFA7PlPr6kvqalKO5/xZoa4bmbp/C/mYlnlPPECVyTzIw2QIr6GdbXrTtXdiqszNI1PLaom15KzGlISCP09jVBdwz+pvHga0ee7GNjXpPu8CjuCb8B94WSCyyE24OUGvMVCkKBBP962QxhlKSn+KlfBvDb0CgYEA6g2pjSKa3SWfyP90fBPb69RRXUMnA3lnlV15i6ofHDfi68neZ3xAJhDwNW1jTZD/192f0ZqFI+fsKW5dVNRbcYXs+cOwBHEY3PXgkAsNbApGslv2PomPZpXz+0r/K2TN9QQIGoZsZ4XmYJqzAL4/q7EtO0xjoN9s8Mrs9eo1IkCgYEAgsHbx0FveGD2l04B0GVVJRT7dhvCiwITFwGrQkMm0X7NHm5LWgREQuYyr2VosJ4g4subFjLKs+mKhRGZgQqC4sHuQjEkhyMJBR2uB3zErUmL7qo29HDk3yrJSughQrQMhsVQXyGcx1UVcBDpZil5BRLyEAyqDN85YMW9MdRws3ECgYAPBzGLzl0DNhc8YKqyIav4D9m4C/vzSTElKXeYgAZxdw3jeiues3V2BFDVYON3XbSgAREquuq0x0QJo5p03hSsZ7u94WghDQL/H8EGq/gqulTpU2XLGMS7z90zjJb2cm6xdvxSGH3t2ajKQoV48/fo4m/e7hvweqDnmfCEa6R7gQKBgHMOd+yQrHC9MO0Hmy/ku9oYWF/E5fONXJa/DibYQphMM5vn9V2QyJSt3sgzlaaJSuclGQ0BsEjXjJ1BbX0Y9YNIn2/A459TLvxoBPm+3aXIb83tQ6AhslIwqlzxeU3jZOr3OtKWazVI8gGTJh8FmQ7GPbsrY9NZ/hDnvY1XA9VN
        script: |
          sudo docker pull haul123/qogustj:latest
          chmod 777 ./scripts/deploy.sh
          cp ./scripts/deploy.sh ./deploy.sh
          ./deploy.sh
          docker image prune -f
